@echo off
echo ğÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
echo ³                                                                          Ş
echo ³                        Command List of Slave PC                          Ş
echo ³                                                                          Ş
echo ÃÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄŞ
echo ³ Syntax ³   Type "[Commands] /?" to get details information.              Ş
echo ÃÄÄÄÄÄÄÄÄÙ                                                                 Ş
echo ³                                                                          Ş
echo ³  (1) Slave [Slave Name] [Output] [Input]    Í Register a slave          Ş
echo ³  (2) Order [Slave Name] [dos Command]       Í Send order to a slave     Ş
echo ³  (3) Hi    [Slave Name] [Dos Command]       Í Send order to a slave     Ş
echo ³  (4) Run   [Dos Command]                    Í Send order to somebody    Ş
echo ³  (5) View  [Slave Name] [Dos Command]       Í Send order & View output  Ş
echo ³  (6) List                                   Í List slaves               Ş
echo ³  (7) Release [Slave Name]³[ALL]             Í Release slave, thanks     Ş
echo ³                                                                          Ş
echo ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄŞ
echo ³                                                                          Ş
echo ³         Copyright 1994, C.K. Hung, HomgKong, All rights reserved         Ş
echo ³         Version 1.01 (Batch Version), Last updated at 19 Dec 94.         Ş
echo ³         Written by C.K.Hung based on an idea of Jeff                     Ş
echo ³                                                                          Ş
echo øßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
echo 
